// Re-export all session functions from JSON-based implementation
export {
  getSession,
  upsertSession,
  updateSession,
  deleteSession,
  clearChromeActive,
  removeScreenshot,
  getAllSessions,
  getSessionPids,
  deleteSessionsByPids,
  cleanupStaleSessions,
  getSessionsDir,
  setSessionsDir,
  type Session,
  type SessionState,
  type SessionInput,
  type SessionUpdate,
  type Screenshot,
  readLinks,
  writeLink,
} from "./sessions-json.js";
